const DEFAULT_LOCALE = 'en';

export const STRINGS = {
  en: {
    common: {
      back: 'Back',
      retry: 'Retry',
      cancel: 'Cancel',
      delete: 'Delete',
      continue: 'Continue',
      dismiss: 'Dismiss',
      refresh: 'Refresh',
      clear: 'Clear',
      loading: 'Loading…',
      skipForNow: 'Skip for now',
    },
    onboarding: {
      appName: 'Farm Assistant',
      tagline: 'Your AI-powered farming companion',
      getStarted: 'Get Started',
      features: {
        weatherTitle: 'Weather Forecasts',
        weatherDescription: 'Get accurate weather predictions for your farm',
        diagnosisTitle: 'Crop Diagnosis',
        diagnosisDescription: 'Identify plant diseases with photos',
        voiceTitle: 'Voice Support',
        voiceDescription: 'Speak naturally in your language',
      },
      locationTitle: 'Enable Location',
      locationDescription:
        'Share your location to get accurate weather forecasts and region-specific farming advice.',
      enableLocation: 'Enable Location',
      locationDenied: 'Location permission denied',
      locationError: 'Could not get location. Please try again.',
      benefits: {
        weather: 'Local weather forecasts',
        regionAdvice: 'Region-specific crop advice',
        soilData: 'Soil data for your area',
      },
      languageTitle: 'Select Language',
      languageSubtitle: 'Choose your preferred language for the assistant',
      searchLanguages: 'Search languages...',
      noLanguagesFound: 'No languages found',
    },
    chat: {
      welcomeMessage:
        "Hello! 👋 I'm your farming assistant.\n\nI can help you with:\n• Crops, vegetables, fruits, and flowers\n• Livestock, poultry, and fish farming\n• Pest and disease management\n• Weather and market advice\n\nHow can I help you today?",
      locationDenied: 'Location permission denied',
      locationUpdated: 'Location updated!',
      locationUpdateFailed: 'Could not update location',
      loadingConversation: 'Loading conversation...',
      thinking: 'Thinking...',
      messagePlaceholder: 'Message...',
      fromVoice: 'From voice — edit if needed',
      voiceTranscribed: 'Voice transcribed! Edit if needed, then send.',
      noInternet: 'No internet connection. Please check your network.',
      couldNotLoadConversation: 'Could not load conversation',
      startedNewConversation: 'Started new conversation',
      connectionErrorBot: 'Connection error. Please try again.',
      analyzingPlantImage: 'Analyzing plant image...',
      imageAnalysisFailedBot: 'Image analysis failed. Please try again.',
      sorryCouldNotProcess: "Sorry, I couldn't process that. {details}",
      analysisCouldNotComplete: "Analysis couldn't complete. {details}",
      plantAnalysisIssues: 'Plant analysis had issues: {details}',
      tapLocationToSet: 'Tap location to set',
      senderAssistant: 'Farm Assistant',
      senderYou: 'You',
      tapToAskNext: 'Tap to ask next:',
    },
    media: {
      photoLibraryPermission:
        'Photo library access is needed to select images. Enable in Settings.',
      cameraPermission: 'Camera access is needed to take photos. Enable in Settings.',
      pickImageFailed: 'Failed to pick image. Please try again.',
      cameraFailed: 'Failed to access camera. Please try again.',
    },
    voice: {
      microphonePermission: 'Microphone permission required',
      startRecordingFailed: 'Failed to start recording',
      recordingFailed: 'Recording failed',
      transcriptionFailed: 'Transcription failed',
      couldNotTranscribeAudio: 'Could not transcribe audio',
      voiceUnavailableLater: 'Voice unavailable - please try again later',
      voiceUnavailable: 'Voice unavailable - please try again',
      audioPlaybackFailed: 'Audio playback failed',
      recording: 'Recording',
      cancel: 'Cancel',
      done: 'Done',
      transcribing: 'Transcribing...',
      recordingHint: 'Tap Done to transcribe, or Cancel to discard',
    },
    history: {
      title: 'Conversations',
      noConversations: 'No conversations yet',
      noConversationsHint: 'Start a new chat to get farming advice',
      newChat: 'New Chat',
      newConversation: 'New Conversation',
      deleteTitle: 'Delete Conversation',
      deleteMessage: 'Delete "{title}"? This cannot be undone.',
      untitled: 'Untitled',
      deleted: 'Conversation deleted',
      deleteFailed: 'Delete failed',
      couldNotDelete: 'Could not delete conversation',
      notConnectedTitle: 'Not connected',
      notConnectedHint: 'Conversation history requires an internet connection',
      yesterday: 'Yesterday',
    },
    settings: {
      title: 'Settings',
      sectionConversations: 'CONVERSATIONS',
      sectionAiServices: 'AI SERVICES',
      sectionLocation: 'LOCATION',
      sectionLanguage: 'LANGUAGE',
      sectionAppearance: 'APPEARANCE',
      sectionDanger: 'DANGER ZONE',
      chatHistory: 'Chat History',
      chatHistorySubtitle: 'View and continue past conversations',
      aiServices: 'Active Services',
      aiServicesSubtitle: 'View AI services active for your region',
      locationPermissionDenied: 'Location permission denied',
      locationUpdated: 'Location updated successfully!',
      locationUpdateFailed: 'Could not update location. Please try again.',
      locationEnabled: 'Location enabled',
      tapToEnable: 'Tap to enable',
      tapToUpdateLocation: 'Tap to update location',
      themeLight: 'Light',
      themeDark: 'Dark',
      themeSystem: 'System',
      language: 'Language',
      resetOnboarding: 'Reset Onboarding',
      resetOnboardingSubtitle: 'Start fresh with setup wizard',
      resetConfirmTitle: 'Reset Setup',
      resetConfirmMessage: 'This will restart the onboarding process. Continue?',
      appInfoVersion: 'Farm Assistant v2.0.0',
      appInfoPoweredBy: 'Powered by Gemini AI',
    },
    mcp: {
      title: 'AI Integrations',
      loading: 'Loading integrations...',
      footer: 'Integrations activate based on your region. Pull to refresh.',
      couldNotLoad: 'Could not load services',
      serviceCategory: 'Category {name}',
      service: 'Service {name}',
      stats: {
        active: 'Active',
        issues: 'Issues',
        inactive: 'Inactive',
        total: 'Total',
      },
      locationNotSet: 'Location not set',
    },
    system: {
      offline: 'No internet connection',
      errorTitle: 'Oops! Something went wrong',
      errorFallback: 'An unexpected error occurred',
      tryAgain: 'Try Again',
    },
    a11y: {
      startNewChat: 'Start a new chat',
      retryLoadingIntegrations: 'Retry loading integrations',
      dismissNotification: 'Dismiss notification',
      dismiss: 'Dismiss',
      clearSearch: 'Clear search',
      cancelRecording: 'Cancel recording',
      finishRecording: 'Finish recording',
      refreshLocation: 'Refresh location',
      newChat: 'New chat',
      openSettings: 'Open settings',
      scrollToBottom: 'Scroll to bottom',
      clearVoiceTranscription: 'Clear voice transcription',
      takePhoto: 'Take photo',
      pickImage: 'Pick image',
      messageInput: 'Message input',
      sendMessage: 'Send message',
      recordVoice: 'Record voice',
    },
  },
};

function getByPath(obj, path) {
  const parts = path.split('.');
  let current = obj;
  for (const part of parts) {
    if (!current || typeof current !== 'object') return undefined;
    current = current[part];
  }
  return current;
}

export function t(key, params) {
  const raw = getByPath(STRINGS[DEFAULT_LOCALE], key) ?? key;
  if (!params) return raw;
  return Object.keys(params).reduce((acc, k) => acc.replaceAll(`{${k}}`, String(params[k])), raw);
}
