/**
 * English strings - default language
 * All other translations are based on this file
 */

export const en = {
  common: {
    back: 'Back',
    retry: 'Retry',
    cancel: 'Cancel',
    delete: 'Delete',
    continue: 'Continue',
    dismiss: 'Dismiss',
    refresh: 'Refresh',
    clear: 'Clear',
    loading: 'Loading…',
    skipForNow: 'Skip for now',
    comingSoon: 'Coming soon',
  },
  onboarding: {
    appName: 'FarmerChat',
    tagline: 'Your AI-powered farming companion',
    getStarted: 'Get Started',
    features: {
      weatherTitle: 'Weather Forecasts',
      weatherDescription: 'Get accurate weather predictions for your farm',
      diagnosisTitle: 'Crop Diagnosis',
      diagnosisDescription: 'Identify plant diseases with photos',
      voiceTitle: 'Voice Support',
      voiceDescription: 'Speak naturally in your language',
    },
    locationTitle: 'Enable Location',
    locationDescription:
      'Share your location to get accurate weather forecasts and region-specific farming advice.',
    enableLocation: 'Enable Location',
    locationDenied: 'Location permission denied',
    locationError: 'Could not get location. Please try again.',
    gpsFailed: 'GPS unavailable, using your network location...',
    usingIpLocation: 'Using your network location instead...',
    selectLocation: 'Select Your Location',
    selectLocationMessage: 'Could not detect your location automatically. Please select your region:',
    benefits: {
      weather: 'Local weather forecasts',
      regionAdvice: 'Region-specific crop advice',
      soilData: 'Soil data for your area',
    },
    languageTitle: 'Select Language',
    languageSubtitle: 'Choose your preferred language for the assistant',
    searchLanguages: 'Search languages...',
    noLanguagesFound: 'No languages found',
    suggestedForYou: 'Suggested for You',
    currentLanguage: 'Current',
  },
  chat: {
    welcomeMessage:
      "Hello! 👋 I'm your farming assistant.\n\nI can help you with:\n• Crops, vegetables, fruits, and flowers\n• Livestock, poultry, and fish farming\n• Pest and disease management\n• Weather and market advice\n\nHow can I help you today?",
    locationDenied: 'Location permission denied',
    locationUpdated: 'Location updated!',
    gpsLocationUpdated: 'GPS location updated!',
    gpsFailed: 'GPS unavailable, using IP location...',
    ipLocationUpdated: 'Location set to {location}',
    locationUpdateFailed: 'Could not update location',
    loadingConversation: 'Loading conversation...',
    thinking: 'Thinking...',
    messagePlaceholder: 'Message...',
    fromVoice: 'From voice — edit if needed',
    voiceTranscribed: 'Voice transcribed! Edit if needed, then send.',
    noInternet: 'No internet connection. Please check your network.',
    couldNotLoadConversation: 'Could not load conversation',
    startedNewConversation: 'Started new conversation',
    connectionErrorBot: 'Connection error. Please try again.',
    servicesWarmingUp: 'Services warming up, retrying...',
    plantPhotoSent: 'Sent plant photo for analysis',
    analyzingImage: 'Analyzing your image...',
    analyzeImage: 'Analyzing your image...',
    analyseImage: 'Analyzing your image...',
    imageAnalyzed: 'Plant image',
    imageAnalysisFailed: 'Image analysis failed',
    imageAnalysisFailedBot: 'Image analysis failed. Please try again.',
    sorryCouldNotProcess: "Sorry, I couldn't process that. {details}",
    analysisCouldNotComplete: "Analysis couldn't complete. {details}",
    plantAnalysisIssues: 'Plant analysis had issues: {details}',
    tapLocationToSet: 'Tap location to set',
    setLocation: 'Set your location',
    updatingLocation: 'Updating location...',
    senderAssistant: 'FarmerChat',
    senderYou: 'You',
    tapToAskNext: 'Tap to ask next:',
    analysisComplete: 'Analysis complete',
    lowAccuracy: 'Low Accuracy',
    tapToImprove: 'Tap to improve',
  },
  media: {
    photoLibraryPermission:
      'Photo library access is needed to select images. Enable in Settings.',
    cameraPermission: 'Camera access is needed to take photos. Enable in Settings.',
    pickImageFailed: 'Failed to pick image. Please try again.',
    cameraFailed: 'Failed to access camera. Please try again.',
    camera: 'Camera',
    gallery: 'Gallery',
    addToChat: 'Upload Image',
    uploadHint: 'Take or select a photo for plant health diagnosis',
    photos: 'Photos',
  },
  voice: {
    microphonePermission: 'Microphone permission required',
    startRecordingFailed: 'Failed to start recording',
    recordingFailed: 'Recording failed',
    transcriptionFailed: 'Transcription failed',
    couldNotTranscribeAudio: 'Could not transcribe audio',
    voiceUnavailableLater: 'Voice unavailable - please try again later',
    voiceUnavailable: 'Voice unavailable - please try again',
    audioPlaybackFailed: 'Audio playback failed',
    recording: 'Recording',
    cancel: 'Cancel',
    done: 'Done',
    transcribing: 'Transcribing...',
    recordingHint: 'Tap Done to transcribe, or Cancel to discard',
    listening: 'Listening...',
    waitingForSpeech: 'Waiting for speech...',
    liveTranscription: 'Live transcription',
    languageMismatch: 'Please speak in {expected}. Your speech was detected as {detected}.',
    noSpeechDetected: 'No speech detected. Please speak clearly and try again.',
    audioTooShort: 'Recording too short. Please speak for at least 1 second.',
    audioQualityPoor: 'Audio quality too low. Try again in a quieter environment.',
    connecting: 'Connecting...',
    reconnecting: 'Reconnecting...',
    connectionError: 'Connection error',
  },
  history: {
    title: 'Conversations',
    noConversations: 'No conversations yet',
    noConversationsHint: 'Start a new chat to get farming advice',
    newChat: 'New Chat',
    newConversation: 'New Conversation',
    deleteTitle: 'Delete Conversation',
    deleteMessage: 'Delete "{title}"? This cannot be undone.',
    untitled: 'Untitled',
    deleted: 'Conversation deleted',
    deleteFailed: 'Delete failed',
    couldNotDelete: 'Could not delete conversation',
    notConnectedTitle: 'Not connected',
    notConnectedHint: 'Conversation history requires an internet connection',
    yesterday: 'Yesterday',
    messageCount: '{count} messages',
    messageCountSingular: '1 message',
  },
  settings: {
    title: 'Settings',
    sectionConversations: 'CONVERSATIONS',
    sectionAiServices: 'ag-mcp',
    sectionLocation: 'LOCATION',
    sectionLanguage: 'LANGUAGE',
    sectionAppearance: 'APPEARANCE',
    sectionDanger: 'DANGER ZONE',
    chatHistory: 'Chat History',
    chatHistorySubtitle: 'View and continue past conversations',
    aiServices: 'Active Services',
    aiServicesSubtitle: 'View AI services active for your region',
    locationPermissionDenied: 'Location permission was denied. Enable in device Settings.',
    locationUpdated: 'Location updated!',
    locationUpdateFailed: 'Could not get your location',
    gpsLocationUpdated: 'GPS location updated!',
    gpsFailed: 'GPS unavailable, using IP location...',
    ipLocationUpdated: 'Location set to {location}',
    locationFallbackTitle: 'Select Your Location',
    locationFallbackMessage: 'Could not detect your location automatically. Please select your region:',
    locationEnabled: 'Location enabled',
    locationNotSet: 'Location not set',
    locationHint: 'Tap to use GPS',
    updatingLocation: 'Getting location...',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    language: 'Language',
    resetOnboarding: 'Reset Onboarding',
    resetOnboardingSubtitle: 'Start fresh with setup wizard',
    resetConfirmTitle: 'Reset Setup',
    resetConfirmMessage: 'This will restart the onboarding process. Continue?',
    appInfoVersion: 'FarmerChat v2.0.0',
    appInfoPoweredBy: 'Powered by Digital Green Foundation',
  },
  mcp: {
    title: 'ag-mcp',
    description: 'An initiative by Digital Green Foundation',
    loading: 'Loading services...',
    loadingDetails: 'Loading...',
    footer: 'Service availability depends on your location',
    couldNotLoad: 'Could not load services',
    couldNotLoadDetails: 'Could not load service details',
    failedToFetch: 'Failed to fetch services',
    serviceCategory: 'Category {name}',
    service: 'Service {name}',
    servicesAvailable: '{active} of {total} services available for your location',
    activeCount: '{active}/{total} active',
    statusActive: 'Active',
    statusUnavailable: 'Not available in your region',
    locationNotSet: 'Location not set',
    selectPreferred: 'Select your preferred provider',
    preferencesSaved: 'Preference saved',
    comingSoon: 'Coming Soon',
    inUse: 'In Use',
    sectionAbout: 'About',
    sectionFeatures: 'Features',
    sectionAvailableIn: 'Available In',
    sectionSupportedCrops: 'Supported Crops',
    categories: {
      plantHealth: 'Plant Health',
      soil: 'Soil Analysis',
      weather: 'Weather & Climate',
      livestock: 'Livestock Nutrition',
      agriculture: 'Crop Advisory',
    },
    services: {
      agrivision: {
        name: 'AgriVision',
        tagline: 'AI-powered plant disease detection and diagnosis',
        description: 'Analyze plant images to identify diseases, pests, and nutrient deficiencies.',
      },
      plantix: {
        name: 'Plantix',
        tagline: 'Plant disease diagnosis with 21 language support',
        description: 'Identify plant diseases from photos using Plantix AI.',
      },
      isdaSoil: {
        name: 'ISDA Soil',
        tagline: 'Soil properties and nutrient analysis for Africa',
        description: 'Get detailed soil information including pH, nitrogen, phosphorus, potassium.',
      },
      accuweather: {
        name: 'AccuWeather',
        tagline: 'Current conditions and weather forecasts worldwide',
        description: 'Access real-time weather data including temperature, humidity, wind speed.',
      },
      gapWeather: {
        name: 'GAP Weather',
        tagline: 'Agricultural weather forecasts for Kenya',
        description: 'Specialized weather forecasts for agriculture in Kenya.',
      },
      edacap: {
        name: 'EDACaP Climate',
        tagline: 'Seasonal climate forecasts for Ethiopia',
        description: 'Seasonal climate outlook including temperature and rainfall predictions.',
      },
      weatherapi: {
        name: 'WeatherAPI',
        tagline: 'Weather data for global locations',
        description: 'Comprehensive weather data service for locations worldwide.',
      },
      tomorrowIo: {
        name: 'Tomorrow.io',
        tagline: 'Weather intelligence and forecasting',
        description: 'Advanced weather intelligence platform with high-resolution forecasts.',
      },
      feedFormulation: {
        name: 'Feed Formulation',
        tagline: 'Optimal diet calculations for dairy cattle',
        description: 'Calculate the most cost-effective feed mix for your dairy cattle.',
      },
      nextgen: {
        name: 'NextGen Fertilizer',
        tagline: 'Site-specific fertilizer recommendations for Ethiopia',
        description: 'Get precise fertilizer recommendations based on your exact location.',
      },
      decisionTree: {
        name: 'Crop Decision Tree',
        tagline: 'Growth stage recommendations for Kenya',
        description: 'Get crop management recommendations based on growth stage.',
      },
      gapAgriculture: {
        name: 'GAP Agriculture',
        tagline: 'Agricultural advisory services',
        description: 'General agricultural advisory services for crop and livestock management.',
      },
    },
    features: {
      diseaseDetection: 'Disease Detection',
      pestIdentification: 'Pest Identification',
      nutrientAnalysis: 'Nutrient Analysis',
      treatmentAdvice: 'Treatment Advice',
      cropIdentification: 'Crop Identification',
      soilPh: 'Soil pH',
      nitrogen: 'Nitrogen',
      phosphorus: 'Phosphorus',
      potassium: 'Potassium',
      currentWeather: 'Current Weather',
      temperature: 'Temperature',
      humidity: 'Humidity',
      forecast: 'Forecast',
      precipitation: 'Precipitation',
      evapotranspiration: 'Evapotranspiration',
      solarRadiation: 'Solar Radiation',
      wind: 'Wind',
      seasonalOutlook: 'Seasonal Outlook',
      rainfallProbability: 'Rainfall Probability',
      temperatureTrend: 'Temperature Trend',
      cropForecasts: 'Crop Forecasts',
      historical: 'Historical',
      astronomy: 'Astronomy',
      nowcast: 'Nowcast',
      forecasts: 'Forecasts',
      alerts: 'Alerts',
      dietOptimization: 'Diet Optimization',
      nutrientBalance: 'Nutrient Balance',
      localFeeds: 'Local Feeds',
      costCalculation: 'Cost Calculation',
      organicFertilizers: 'Organic Fertilizers',
      inorganicFertilizers: 'Inorganic Fertilizers',
      expectedYield: 'Expected Yield',
      siteSpecific: 'Site-Specific',
      growthStage: 'Growth Stage',
      recommendations: 'Recommendations',
      weatherBased: 'Weather-Based',
      actions: 'Actions',
      cropAdvice: 'Crop Advice',
      bestPractices: 'Best Practices',
      seasonalTips: 'Seasonal Tips',
      localKnowledge: 'Local Knowledge',
    },
    fallback: {
      service: 'Agricultural service',
      description: 'Service details not available.',
    },
    regions: {
      worldwide: 'Worldwide',
      africa: 'Africa',
      eastAfrica: 'East Africa',
      ethiopia: 'Ethiopia',
      kenya: 'Kenya',
    },
    crops: {
      all: 'All crops',
      wheat: 'Wheat',
      maize: 'Maize',
      beans: 'Beans',
    },
  },
  system: {
    offline: 'No internet connection',
    errorTitle: 'Oops! Something went wrong',
    errorFallback: 'An unexpected error occurred',
    tryAgain: 'Try Again',
    restartRequired: 'App Restart Required',
    restartRequiredMessage: 'Switching to {language} requires restarting the app for layout changes.',
    restartNow: 'Restart Now',
    pleaseRestart: 'Please Restart',
    pleaseRestartMessage: 'Please close and reopen the app for changes to take effect.',
  },
  errors: {
    syncFailed: 'Could not connect to server. Some features may be limited.',
    weatherUnavailable: 'Weather service is temporarily unavailable. Try again later.',
    diagnosisTimeout: 'Plant diagnosis is taking too long. Please try again.',
    uploadFailed: 'Could not upload image. Check your connection and retry.',
    transcriptionFailed: 'Voice transcription failed. Try speaking again.',
    serverError: 'Server error. Please try again later.',
    requestTimeout: 'Request timed out. Check your connection.',
    locationLookupFailed: 'Could not determine your location details.',
    imageUploadFailed: 'Image could not be saved. Your message was sent.',
    audioUploadFailed: 'Voice recording could not be saved.',
    mcpServersFailed: 'Could not load AI services. Some features may be unavailable.',
    sessionCreateFailed: 'Could not save conversation. Messages may not persist.',
  },
  diagnosis: {
    analyzed: 'Analyzed',
    plant: 'Plant',
    quality: 'Quality',
    confidence: 'Confidence',
    analyzedVia: 'Analyzed via AgriVision',
    crop: 'Crop',
    status: 'Status',
    stage: 'Stage',
    issueDetected: 'Issue Detected',
    treatment: 'Treatment',
    organic: 'Organic',
    chemical: 'Chemical',
    severity: 'Severity',
    symptoms: 'Symptoms',
    healthyTitle: 'Healthy Plant',
    healthyMessage: 'Your plant appears healthy! No diseases or issues were detected.',
    healthyTips: 'Tips to keep it healthy:',
    healthyTipMonitor: 'Monitor regularly for early signs of problems',
    healthyTipWater: 'Maintain proper watering schedule',
    healthyTipNutrition: 'Ensure adequate nutrition and sunlight',
    networkErrorTitle: 'Connection Error',
    networkErrorMessage: 'Could not analyze your image. Please check your internet connection.',
    timeoutTitle: 'Analysis Timed Out',
    timeoutMessage: 'The analysis is taking too long. Try again with a clearer photo.',
    notPlantTitle: 'Not a Plant Image',
    notPlantMessage: 'This doesn\'t appear to be a plant image. Please take a photo of a plant.',
    poorQualityTitle: 'Image Quality Too Low',
    poorQualityMessage: 'The image is too blurry or dark for accurate diagnosis.',
    screenshotTitle: 'Screenshot Detected',
    screenshotMessage: 'This appears to be a screenshot. Please take a direct photo.',
    textImageTitle: 'Text/Document Detected',
    textImageMessage: 'This appears to be text. Please take a photo of the actual plant.',
    guardrailTitle: 'Image Not Accepted',
    guardrailMessage: 'This image cannot be processed. Please take a clear photo.',
    tipsForBetterPhoto: 'Tips for a better photo:',
    tipsForBetterResults: 'Tips for better results:',
    tipCloseUp: 'Take a close-up of the plant',
    tipFocusArea: 'Focus on the affected area',
    tipLighting: 'Ensure good lighting',
    tipGoodLighting: 'Use good lighting',
    tipSteady: 'Hold camera steady',
    tipHoldSteady: 'Hold your phone steady',
    tipCloser: 'Move closer to the plant',
    tipDaylight: 'Use natural daylight',
    tipsToTry: 'You can try:',
    tipBetterSignal: 'Move to an area with better signal',
    tipSmallerImage: 'Use a smaller or clearer image',
    tipWaitRetry: 'Wait a moment and retry',
    retry: 'Retry',
    tryAgain: 'Try Again',
    takeBetterPhoto: 'Take Better Photo',
  },
  a11y: {
    startNewChat: 'Start a new chat',
    retryLoadingIntegrations: 'Retry loading integrations',
    dismissNotification: 'Dismiss notification',
    dismiss: 'Dismiss',
    clearSearch: 'Clear search',
    cancelRecording: 'Cancel recording',
    finishRecording: 'Finish recording',
    refreshLocation: 'Refresh location',
    newChat: 'New chat',
    openSettings: 'Open settings',
    scrollToBottom: 'Scroll to bottom',
    clearVoiceTranscription: 'Clear voice transcription',
    takePhoto: 'Take photo',
    pickImage: 'Pick image',
    messageInput: 'Message input',
    sendMessage: 'Send message',
    recordVoice: 'Record voice',
    attachMedia: 'Attach media',
    closeMenu: 'Close menu',
    openHistory: 'Open chat history',
    playVoice: 'Play voice',
    stopVoicePlayback: 'Stop voice playback',
    moreNotifications: '{count} more notifications',
    themeMode: 'Theme: {mode}',
    copyMessage: 'Copy message',
    askQuestion: 'Ask: {question}',
    selectLanguage: 'Language {name}',
  },
  weather: {
    current: 'Current Weather',
    forecast: 'Forecast',
    high: 'High',
    low: 'Low',
    humidity: 'Humidity',
    wind: 'Wind',
    precipitation: 'Precipitation',
    feelsLike: 'Feels like',
    uvIndex: 'UV Index',
    visibility: 'Visibility',
    alert: 'Weather Alert',
    alertDismiss: 'Dismiss',
    loading: 'Loading weather...',
    today: 'Today',
    windUnit: 'km/h',
    dataFrom: 'Data from',
    daySun: 'Sun',
    dayMon: 'Mon',
    dayTue: 'Tue',
    dayWed: 'Wed',
    dayThu: 'Thu',
    dayFri: 'Fri',
    daySat: 'Sat',
    tapForDetails: 'Tap for details',
    yourLocation: 'Your Location',
  },
  content: {
    forYou: 'For You',
    seeAll: 'See All',
    readMore: 'Read More',
    listen: 'Listen',
    watch: 'Watch',
    minutesRead: '{minutes} min read',
    related: 'Related',
    share: 'Share',
    like: 'Like',
    noContent: 'No content available',
    loadError: 'Could not load content',
    notFound: 'Content not found',
  },
  home: {
    quickActions: 'Quick Actions',
    askQuestion: 'Ask a Question',
    takePhoto: 'Diagnose Plant',
    viewHistory: 'Chat History',
    refresh: 'Pull to refresh',
  },
  notifications: {
    title: 'Notifications',
    settings: 'Notification Settings',
    weatherAlerts: 'Weather Alerts',
    contentUpdates: 'Content Updates',
    engagement: 'Tips & Reminders',
    enable: 'Enable Notifications',
    disabled: 'Notifications are disabled',
  },
};

export type StringsType = typeof en;
