/**
 * English strings - default language
 * All other translations are based on this file
 */

export const en = {
  common: {
    back: 'Back',
    retry: 'Retry',
    cancel: 'Cancel',
    delete: 'Delete',
    continue: 'Continue',
    dismiss: 'Dismiss',
    refresh: 'Refresh',
    clear: 'Clear',
    loading: 'Loading…',
    somethingWentWrong: 'Something went wrong',
    yes: 'Yes',
    no: 'No',
    submit: 'Submit',
    save: 'Save',
    skipForNow: 'Skip for now',
    comingSoon: 'Coming soon',
  },
  tabs: {
    chat: 'Chat',
    farms: 'Farms',
    livestock: 'Livestock',
    farmers: 'Farmers',
    settings: 'Settings',
  },
  onboarding: {
    appName: 'FarmerChat',
    tagline: 'Your AI-powered farming companion',
    getStarted: 'Get Started',
    features: {
      weatherTitle: 'Weather Forecasts',
      weatherDescription: 'Get accurate weather predictions for your farm',
      diagnosisTitle: 'Crop Diagnosis',
      diagnosisDescription: 'Identify plant diseases with photos',
      voiceTitle: 'Voice Support',
      voiceDescription: 'Speak naturally in your language',
    },
    // Location screen
    locationTitle: 'Share Your Location',
    locationDescription:
      'Share your exact location via GPS to get more accurate weather forecasts and hyper-local farming advice.',
    enableLocation: 'Share GPS Location',
    locationDenied: 'Location permission denied',
    locationError: 'Could not get location. Please try again.',
    gpsFailed: 'GPS unavailable, using your network location...',
    usingIpLocation: 'Using your network location instead...',
    selectLocation: 'Select Your Location',
    selectLocationMessage: 'Could not detect your location automatically. Please select your region:',
    detectedLocation: 'Detected location:',
    detectedLocationFrom: 'Detected from your network',
    gpsShareBenefit: 'GPS sharing gives you more accurate, field-level weather and soil data',
    continueWithDetected: 'Continue with detected location',
    benefits: {
      weather: 'Hyper-local weather forecasts',
      regionAdvice: 'Field-level crop advice',
      soilData: 'Precise soil data for your exact location',
    },
    // Language screen
    languageTitle: 'Select Language',
    languageSubtitle: 'Choose your preferred language for the assistant',
    languageDetected: 'Language detected for {country}',
    languageDetectedGeneric: 'Language detected from your location',
    changeLanguage: 'Change language',
    confirmLanguage: 'Confirm & Continue',
    searchLanguages: 'Search languages...',
    noLanguagesFound: 'No languages found',
    suggestedForYou: 'Suggested for You',
    currentLanguage: 'Current',
    detectedForYou: 'Detected for you',
  },
  chat: {
    welcomeMessage:
      "Hello! 👋 I'm your farming assistant.\n\nI can help you with:\n• Crops, vegetables, fruits, and flowers\n• Livestock, poultry, and fish farming\n• Pest and disease management\n• Weather and market advice\n\nHow can I help you today?",
    locationDenied: 'Location permission denied',
    locationUpdated: 'Location updated!',
    gpsLocationUpdated: 'GPS location updated!',
    gpsFailed: 'GPS unavailable, using IP location...',
    ipLocationUpdated: 'Location set to {location}',
    locationUpdateFailed: 'Could not update location',
    loadingConversation: 'Loading conversation...',
    thinking: 'Thinking...',
    today: 'Today',
    yesterday: 'Yesterday',
    messagePlaceholder: 'Message...',
    fromVoice: 'From voice — edit if needed',
    voiceTranscribed: 'Voice transcribed! Edit if needed, then send.',
    noInternet: 'No internet connection. Please check your network.',
    couldNotLoadConversation: 'Could not load conversation',
    startedNewConversation: 'Started new conversation',
    connectionErrorBot: 'Connection error. Please try again.',
    servicesWarmingUp: 'Services warming up, retrying...',
    plantPhotoSent: 'Sent plant photo for analysis',
    analyzingImage: 'Analyzing your image...',
    analyzeImage: 'Analyzing your image...',
    analyseImage: 'Analyzing your image...',
    imageAnalyzed: 'Plant image',
    imageAnalysisFailed: 'Image analysis failed',
    imageAnalysisFailedBot: 'Image analysis failed. Please try again.',
    sorryCouldNotProcess: "Sorry, I couldn't process that. {details}",
    analysisCouldNotComplete: "Analysis couldn't complete. {details}",
    plantAnalysisIssues: 'Plant analysis had issues: {details}',
    tapLocationToSet: 'Tap location to set',
    setLocation: 'Set your location',
    updatingLocation: 'Updating location...',
    senderAssistant: 'FarmerChat',
    senderYou: 'You',
    tapToAskNext: 'Tap to ask next:',
    askButton: 'Ask 👆',
    starterQuestionsHeader: 'Try asking:',
    starterQuestionsLoading: 'Getting suggestions for you...',
    followUpQuestionsHeader: 'You might also ask:',
    analysisComplete: 'Analysis complete',
    lowAccuracy: 'Low Accuracy',
    tapToImprove: 'Tap to improve',
    profileSaveFailed: 'Could not save to profile. Please try again.',
    // A2UI picker modals
    selectCrop: 'Select Crop',
    selectLivestockType: 'Select Livestock Type',
    searchCrops: 'Search crops...',
    searchLivestock: 'Search livestock...',
    suggested: 'Suggested',
    loadingCrops: 'Loading crops...',
    noCropsFound: 'No crops found',
    loadingLivestock: 'Loading livestock...',
    noLivestockFound: 'No livestock found',
    nameOptional: 'Name (optional)',
    namePlaceholder: 'e.g. Aster, Bessie',
    herdSizeOptional: 'Herd size (optional)',
    herdSizePlaceholder: 'e.g. 5',
    addButton: 'Add',
    profileSaved: 'Saved to your profile!',
    stopGenerating: 'Stop',
  },
  media: {
    photoLibraryPermission:
      'Photo library access is needed to select images. Enable in Settings.',
    cameraPermission: 'Camera access is needed to take photos. Enable in Settings.',
    pickImageFailed: 'Failed to pick image. Please try again.',
    cameraFailed: 'Failed to access camera. Please try again.',
    camera: 'Camera',
    gallery: 'Gallery',
    addToChat: 'Upload Image',
    uploadHint: 'Take or select a photo for plant health diagnosis',
    photos: 'Photos',
    preview: 'Preview',
    send: 'Send',
  },
  phone: {
    changeCountry: 'Change country code',
    selectCountry: 'Select Country',
    searchCountry: 'Search country or dial code...',
    popular: 'Popular',
    allCountries: 'All Countries',
    placeholder: 'Phone number',
    invalidNumber: 'Invalid phone number',
  },
  voice: {
    microphonePermission: 'Microphone permission required',
    startRecordingFailed: 'Failed to start recording',
    recordingFailed: 'Recording failed',
    transcriptionFailed: 'Transcription failed',
    couldNotTranscribeAudio: 'Could not transcribe audio',
    voiceUnavailableLater: 'Voice unavailable - please try again later',
    voiceUnavailable: 'Voice unavailable - please try again',
    audioPlaybackFailed: 'Audio playback failed',
    recording: 'Recording',
    cancel: 'Cancel',
    done: 'Done',
    transcribing: 'Transcribing...',
    recordingHint: 'Tap Done to transcribe, or Cancel to discard',
    listening: 'Listening...',
    waitingForSpeech: 'Waiting for speech...',
    liveTranscription: 'Live transcription',
    languageMismatch: 'Please speak in {expected}. Your speech was detected as {detected}.',
    noSpeechDetected: 'No speech detected. Please speak clearly and try again.',
    audioTooShort: 'Recording too short. Please speak for at least 1 second.',
    audioQualityPoor: 'Audio quality too low. Try again in a quieter environment.',
    connecting: 'Connecting...',
    reconnecting: 'Reconnecting...',
    connectionError: 'Connection error',
  },
  history: {
    title: 'Conversations',
    noConversations: 'No conversations yet',
    noConversationsHint: 'Start a new chat to get farming advice',
    searchPlaceholder: 'Search conversations...',
    newChat: 'New Chat',
    newConversation: 'New Conversation',
    deleteTitle: 'Delete Conversation',
    deleteMessage: 'Delete "{title}"? This cannot be undone.',
    untitled: 'Untitled',
    deleted: 'Conversation deleted',
    deleteFailed: 'Delete failed',
    couldNotDelete: 'Could not delete conversation',
    notConnectedTitle: 'Not connected',
    notConnectedHint: 'Conversation history requires an internet connection',
    yesterday: 'Yesterday',
    messageCount: '{count} messages',
    messageCountSingular: '1 message',
  },
  settings: {
    title: 'Settings',
    sectionConversations: 'CONVERSATIONS',
    sectionAiServices: 'ag-mcp',
    sectionLocation: 'LOCATION',
    sectionLanguage: 'LANGUAGE',
    sectionAppearance: 'APPEARANCE',
    sectionDanger: 'DANGER ZONE',
    chatHistory: 'Chat History',
    chatHistorySubtitle: 'View and continue past conversations',
    aiServices: 'Active Services',
    aiServicesSubtitle: 'View AI services active for your region',
    locationPermissionDenied: 'Location permission was denied. Enable in device Settings.',
    locationUpdated: 'Location updated!',
    locationUpdateFailed: 'Could not get your location',
    gpsLocationUpdated: 'GPS location updated!',
    gpsFailed: 'GPS unavailable, using IP location...',
    ipLocationUpdated: 'Location set to {location}',
    locationFallbackTitle: 'Select Your Location',
    locationFallbackMessage: 'Could not detect your location automatically. Please select your region:',
    locationEnabled: 'Location enabled',
    locationNotSet: 'Location not set',
    locationHint: 'Tap to use GPS',
    updatingLocation: 'Getting location...',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    language: 'Language',
    resetOnboarding: 'Reset Onboarding',
    resetOnboardingSubtitle: 'Start fresh with setup wizard',
    resetConfirmTitle: 'Reset Setup',
    resetConfirmMessage: 'This will restart the onboarding process. Continue?',
    sectionAccessibility: 'ACCESSIBILITY',
    textToSpeech: 'Text-to-Speech',
    textToSpeechHint: 'Read assistant messages aloud',
    deleteAccount: 'Delete Account',
    deleteAccountSubtitle: 'Permanently remove all your data',
    deleteAccountTitle: 'Delete Account?',
    deleteAccountMessage: 'This will permanently delete your profile, farms, livestock, chat history, and all associated data. This cannot be undone.',
    deleteAccountConfirmTitle: 'Are you sure?',
    deleteAccountConfirmMessage: 'This action is irreversible. All your data will be permanently deleted.',
    deleteAccountSuccess: 'Account deleted successfully',
    deleteAccountFailed: 'Failed to delete account. Please try again.',
    appInfoVersion: 'FarmerChat v2.0.0',
    appInfoPoweredBy: 'Powered by Digital Green Foundation',
  },
  mcp: {
    title: 'ag-mcp',
    description: 'An initiative by Digital Green Foundation',
    loading: 'Loading services...',
    loadingDetails: 'Loading...',
    footer: 'Service availability depends on your location',
    couldNotLoad: 'Could not load services',
    couldNotLoadDetails: 'Could not load service details',
    failedToFetch: 'Failed to fetch services',
    serviceCategory: 'Category {name}',
    service: 'Service {name}',
    servicesAvailable: '{active} of {total} services available for your location',
    activeCount: '{active}/{total} active',
    statusActive: 'Active',
    statusUnavailable: 'Not available in your region',
    locationNotSet: 'Location not set',
    selectPreferred: 'Select your preferred provider',
    preferencesSaved: 'Preference saved',
    comingSoon: 'Coming Soon',
    inUse: 'In Use',
    sectionAbout: 'About',
    sectionFeatures: 'Features',
    sectionAvailableIn: 'Available In',
    sectionSupportedCrops: 'Supported Crops',
    categories: {
      plantHealth: 'Plant Health',
      soil: 'Soil Analysis',
      weather: 'Weather & Climate',
      livestock: 'Livestock Nutrition',
      agriculture: 'Crop Advisory',
      gap: 'Regional Weather Services',
    },
    services: {
      agrivision: {
        name: 'AgriVision',
        tagline: 'AI-powered plant disease detection and diagnosis',
        description: 'Analyze plant images to identify diseases, pests, and nutrient deficiencies.',
      },
      plantix: {
        name: 'Plantix',
        tagline: 'Plant disease diagnosis with 21 language support',
        description: 'Identify plant diseases from photos using Plantix AI.',
      },
      isdaSoil: {
        name: 'ISDA Soil',
        tagline: 'Soil properties and nutrient analysis for Africa',
        description: 'Get detailed soil information including pH, nitrogen, phosphorus, potassium.',
      },
      accuweather: {
        name: 'AccuWeather',
        tagline: 'Current conditions and weather forecasts worldwide',
        description: 'Access real-time weather data including temperature, humidity, wind speed.',
      },
      gapWeather: {
        name: 'GAP Weather',
        tagline: 'Agricultural weather forecasts for Kenya',
        description: 'Specialized weather forecasts for agriculture in Kenya.',
      },
      edacap: {
        name: 'EDACaP Climate',
        tagline: 'Seasonal climate forecasts for Ethiopia',
        description: 'Seasonal climate outlook including temperature and rainfall predictions.',
      },
      weatherapi: {
        name: 'WeatherAPI',
        tagline: 'Weather data for global locations',
        description: 'Comprehensive weather data service for locations worldwide.',
      },
      tomorrowIo: {
        name: 'Tomorrow.io',
        tagline: 'Weather intelligence and forecasting',
        description: 'Advanced weather intelligence platform with high-resolution forecasts.',
      },
      googleWeather: {
        name: 'Google Weather',
        tagline: 'Global weather with extended forecasts and history',
        description: 'Comprehensive weather data from Google with 10-day forecasts, 240-hour hourly forecasts, and past 24-hour weather history.',
      },
      rationsmart: {
        name: 'RationSmart',
        tagline: 'Smart dairy cattle nutrition for every farm',
        description: 'Create cow profiles and get AI-optimized feed recommendations tailored to your herd.',
      },
      nextgen: {
        name: 'NextGen Fertilizer',
        tagline: 'Site-specific fertilizer recommendations for Ethiopia',
        description: 'Get precise fertilizer recommendations based on your exact location.',
      },
      decisionTree: {
        name: 'Crop Decision Tree',
        tagline: 'Growth stage recommendations for Kenya',
        description: 'Get crop management recommendations based on growth stage.',
      },
      gapAgriculture: {
        name: 'GAP Agriculture',
        tagline: 'Agricultural advisory services',
        description: 'General agricultural advisory services for crop and livestock management.',
      },
    },
    features: {
      diseaseDetection: 'Disease Detection',
      pestIdentification: 'Pest Identification',
      nutrientAnalysis: 'Nutrient Analysis',
      treatmentAdvice: 'Treatment Advice',
      cropIdentification: 'Crop Identification',
      soilPh: 'Soil pH',
      nitrogen: 'Nitrogen',
      phosphorus: 'Phosphorus',
      potassium: 'Potassium',
      currentWeather: 'Current Weather',
      temperature: 'Temperature',
      humidity: 'Humidity',
      forecast: 'Forecast',
      hourlyForecast: 'Hourly Forecast',
      precipitation: 'Precipitation',
      evapotranspiration: 'Evapotranspiration',
      solarRadiation: 'Solar Radiation',
      wind: 'Wind',
      seasonalOutlook: 'Seasonal Outlook',
      rainfallProbability: 'Rainfall Probability',
      temperatureTrend: 'Temperature Trend',
      cropForecasts: 'Crop Forecasts',
      historical: 'Historical',
      astronomy: 'Astronomy',
      nowcast: 'Nowcast',
      forecasts: 'Forecasts',
      alerts: 'Alerts',
      dietOptimization: 'Diet Optimization',
      nutrientBalance: 'Nutrient Balance',
      localFeeds: 'Local Feeds',
      costCalculation: 'Cost Calculation',
      organicFertilizers: 'Organic Fertilizers',
      inorganicFertilizers: 'Inorganic Fertilizers',
      expectedYield: 'Expected Yield',
      siteSpecific: 'Site-Specific',
      growthStage: 'Growth Stage',
      recommendations: 'Recommendations',
      weatherBased: 'Weather-Based',
      actions: 'Actions',
      cropAdvice: 'Crop Advice',
      bestPractices: 'Best Practices',
      seasonalTips: 'Seasonal Tips',
      localKnowledge: 'Local Knowledge',
    },
    fallback: {
      service: 'Agricultural service',
      description: 'Service details not available.',
    },
    regions: {
      worldwide: 'Worldwide',
      africa: 'Africa',
      eastAfrica: 'East Africa',
      ethiopia: 'Ethiopia',
      kenya: 'Kenya',
    },
    crops: {
      all: 'All crops',
      wheat: 'Wheat',
      maize: 'Maize',
      beans: 'Beans',
    },
  },
  system: {
    offline: 'No internet connection',
    errorTitle: 'Oops! Something went wrong',
    errorFallback: 'An unexpected error occurred',
    tryAgain: 'Try Again',
    restartRequired: 'App Restart Required',
    restartRequiredMessage: 'Switching to {language} requires restarting the app for layout changes.',
    restartNow: 'Restart Now',
    pleaseRestart: 'Please Restart',
    pleaseRestartMessage: 'Please close and reopen the app for changes to take effect.',
  },
  errors: {
    syncFailed: 'Could not connect to server. Some features may be limited.',
    weatherUnavailable: 'Weather service is temporarily unavailable. Try again later.',
    diagnosisTimeout: 'Plant diagnosis is taking too long. Please try again.',
    uploadFailed: 'Could not upload image. Check your connection and retry.',
    transcriptionFailed: 'Voice transcription failed. Try speaking again.',
    serverError: 'Server error. Please try again later.',
    requestTimeout: 'Request timed out. Check your connection.',
    locationLookupFailed: 'Could not determine your location details.',
    imageUploadFailed: 'Image could not be saved. Your message was sent.',
    audioUploadFailed: 'Voice recording could not be saved.',
    mcpServersFailed: 'Could not load AI services. Some features may be unavailable.',
    sessionCreateFailed: 'Could not save conversation. Messages may not persist.',
  },
  diagnosis: {
    analyzed: 'Analyzed',
    plant: 'Plant',
    quality: 'Quality',
    confidence: 'Confidence',
    analyzedVia: 'Analyzed via AgriVision',
    crop: 'Crop',
    status: 'Status',
    stage: 'Stage',
    issueDetected: 'Issue Detected',
    treatment: 'Treatment',
    organic: 'Organic',
    chemical: 'Chemical',
    prevention: 'Prevention',
    severity: 'Severity',
    symptoms: 'Symptoms',
    healthyTitle: 'Healthy Plant',
    healthyMessage: 'Your plant appears healthy! No diseases or issues were detected.',
    healthyTips: 'Tips to keep it healthy:',
    healthyTipMonitor: 'Monitor regularly for early signs of problems',
    healthyTipWater: 'Maintain proper watering schedule',
    healthyTipNutrition: 'Ensure adequate nutrition and sunlight',
    networkErrorTitle: 'Connection Error',
    networkErrorMessage: 'Could not analyze your image. Please check your internet connection.',
    timeoutTitle: 'Analysis Timed Out',
    timeoutMessage: 'The analysis is taking too long. Try again with a clearer photo.',
    notPlantTitle: 'Not a Plant Image',
    notPlantMessage: 'This doesn\'t appear to be a plant image. Please take a photo of a plant.',
    poorQualityTitle: 'Image Quality Too Low',
    poorQualityMessage: 'The image is too blurry or dark for accurate diagnosis.',
    screenshotTitle: 'Screenshot Detected',
    screenshotMessage: 'This appears to be a screenshot. Please take a direct photo.',
    textImageTitle: 'Text/Document Detected',
    textImageMessage: 'This appears to be text. Please take a photo of the actual plant.',
    guardrailTitle: 'Image Not Accepted',
    guardrailMessage: 'This image cannot be processed. Please take a clear photo.',
    tipsForBetterPhoto: 'Tips for a better photo:',
    tipsForBetterResults: 'Tips for better results:',
    tipCloseUp: 'Take a close-up of the plant',
    tipFocusArea: 'Focus on the affected area',
    tipLighting: 'Ensure good lighting',
    tipGoodLighting: 'Use good lighting',
    tipSteady: 'Hold camera steady',
    tipHoldSteady: 'Hold your phone steady',
    tipCloser: 'Move closer to the plant',
    tipDaylight: 'Use natural daylight',
    tipsToTry: 'You can try:',
    tipBetterSignal: 'Move to an area with better signal',
    tipSmallerImage: 'Use a smaller or clearer image',
    tipWaitRetry: 'Wait a moment and retry',
    retry: 'Retry',
    tryAgain: 'Try Again',
    takeBetterPhoto: 'Take Better Photo',
  },
  a11y: {
    startNewChat: 'Start a new chat',
    retryLoadingIntegrations: 'Retry loading integrations',
    dismissNotification: 'Dismiss notification',
    dismiss: 'Dismiss',
    clearSearch: 'Clear search',
    cancelRecording: 'Cancel recording',
    finishRecording: 'Finish recording',
    refreshLocation: 'Refresh location',
    newChat: 'New chat',
    openSettings: 'Open settings',
    scrollToBottom: 'Scroll to bottom',
    clearVoiceTranscription: 'Clear voice transcription',
    takePhoto: 'Take photo',
    pickImage: 'Pick image',
    messageInput: 'Message input',
    sendMessage: 'Send message',
    recordVoice: 'Record voice',
    attachMedia: 'Attach media',
    closeMenu: 'Close menu',
    openHistory: 'Open chat history',
    playVoice: 'Play voice',
    stopVoicePlayback: 'Stop voice playback',
    cancelVoiceGeneration: 'Cancel voice generation',
    moreNotifications: '{count} more notifications',
    themeMode: 'Theme: {mode}',
    copyMessage: 'Copy message',
    askQuestion: 'Ask: {question}',
    selectLanguage: 'Language {name}',
    yourMessage: 'Your message',
    imageMessage: 'Image',
    attachedImage: 'Attached image',
  },
  weather: {
    current: 'Current Weather',
    forecast: 'Forecast',
    high: 'High',
    low: 'Low',
    humidity: 'Humidity',
    wind: 'Wind',
    precipitation: 'Precipitation',
    feelsLike: 'Feels like',
    uvIndex: 'UV Index',
    visibility: 'Visibility',
    alert: 'Weather Alert',
    alertDismiss: 'Dismiss',
    loading: 'Loading weather...',
    loadFailed: 'Weather data unavailable',
    pullToRefresh: 'Pull down to refresh',
    today: 'Today',
    windUnit: 'km/h',
    dataFrom: 'Data from',
    daySun: 'Sun',
    dayMon: 'Mon',
    dayTue: 'Tue',
    dayWed: 'Wed',
    dayThu: 'Thu',
    dayFri: 'Fri',
    daySat: 'Sat',
    tapForDetails: 'Tap for details',
    yourLocation: 'Your Location',
  },
  content: {
    forYou: 'For You',
    seeAll: 'See All',
    readMore: 'Read More',
    listen: 'Listen',
    watch: 'Watch',
    minutesRead: '{minutes} min read',
    related: 'Related',
    share: 'Share',
    like: 'Like',
    noContent: 'No content available',
    loadError: 'Could not load content',
    notFound: 'Content not found',
  },
  home: {
    quickActions: 'Quick Actions',
    askQuestion: 'Ask a Question',
    takePhoto: 'Diagnose Plant',
    viewHistory: 'Chat History',
    refresh: 'Pull to refresh',
  },
  notifications: {
    title: 'Notifications',
    settings: 'Notification Settings',
    weatherAlerts: 'Weather Alerts',
    contentUpdates: 'Content Updates',
    engagement: 'Tips & Reminders',
    enable: 'Enable Notifications',
    disabled: 'Notifications are disabled',
  },
  profile: {
    title: 'Profile',
    name: 'Name',
    namePlaceholder: 'Your name',
    phone: 'Phone (optional)',
    phonePlaceholder: '+91 XXXXX XXXXX',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    prefer_not_to_say: 'Prefer not to say',
    role: 'Role',
    roleFarmer: 'Farmer',
    roleExtensionWorker: 'Extension Worker',
    farmingActivities: 'Farming Activities',
    agriculture: 'Agriculture',
    horticulture: 'Horticulture',
    dairy: 'Dairy',
    livestock: 'Livestock',
    poultry: 'Poultry',
    aquaculture: 'Aquaculture',
    completeness: 'Profile Completeness',
    saveProfile: 'Save Profile',
    roleChangeTitle: 'Change Role?',
    roleChangeMessage: 'Changing your role will affect which features are available to you. Are you sure?',
    profileUpdated: 'Profile updated',
    profileUpdateFailed: 'Failed to update profile',
    pictureUpdated: 'Profile picture updated',
    pictureUploadFailed: 'Failed to upload picture',
  },
  farm: {
    myFarms: 'My Farms',
    addFarm: 'Add Farm',
    noFarms: 'No farms yet',
    noFarmsHint: 'Add your first farm to track plots and crops',
    farmName: 'Farm Name',
    farmNamePlaceholder: 'e.g. Main Farm',
    totalArea: 'Total Area (hectares, optional)',
    totalAreaPlaceholder: 'e.g. 2.5',
    newFarm: 'New Farm',
    editFarm: 'Edit Farm',
    deleteFarm: 'Delete Farm',
    deleteFarmConfirm: 'Are you sure you want to delete "{name}"? This will also delete all plots and crop data.',
    farmDeleted: 'Farm deleted',
    farmDeleteFailed: 'Failed to delete farm',
    farmAdded: 'Farm added',
    farmAddFailed: 'Failed to add farm',
    farmUpdated: 'Farm updated',
    farmUpdateFailed: 'Failed to update farm',
    farmNotFound: 'Farm not found',
    enterFarmName: 'Please enter a farm name',
    enterValidArea: 'Please enter a valid area',
    location: 'FARM LOCATION (optional)',
    useGps: 'Use GPS to set location',
    detectingLocation: 'Detecting location…',
    locationSet: 'Farm location set!',
    locationFailed: 'Could not detect location',
    locationPermissionDenied: 'Location permission was denied',
    totalAreaLabel: 'Total Area',
    totalAreaValue: '{area} hectares',
    plots: 'Plots',
    addPlot: 'Add Plot',
    plotsCount: '{count}',
    noPlots: 'No plots yet. Add your first plot to start tracking crops.',
    areaNotSet: 'Area not set',
    sectionMyFarms: 'MY FARMS',
    farmsCount: '{count} farm',
    farmsCountPlural: '{count} farms',
    plotCount: '{count} plot',
    plotCountPlural: '{count} plots',
    noFarmsYetHint: 'Add your first farm to get personalized advice',
  },
  plot: {
    plotName: 'Plot Name',
    plotNamePlaceholder: 'e.g. Plot A',
    area: 'Area (hectares, optional)',
    areaPlaceholder: 'e.g. 0.5',
    soilType: 'Soil Type',
    clay: 'Clay',
    sandy: 'Sandy',
    loamy: 'Loamy',
    silt: 'Silt',
    red: 'Red',
    black: 'Black',
    laterite: 'Laterite',
    alluvial: 'Alluvial',
    irrigation: 'Irrigation',
    rainfed: 'Rainfed',
    irrigated: 'Irrigated',
    mixed: 'Mixed',
    crops: 'Crops',
    addCrop: 'Add',
    noCropsAllocated: 'No crops allocated yet',
    newPlot: 'New Plot',
    editPlot: 'Edit Plot',
    addPlotButton: 'Add Plot',
    saveChanges: 'Save Changes',
    deletePlot: 'Delete Plot',
    deletePlotConfirm: 'Delete "{name}" and all its crop data?',
    plotDeleted: 'Plot deleted',
    plotDeleteFailed: 'Failed to delete plot',
    plotAdded: 'Plot added',
    plotAddFailed: 'Failed to add plot',
    plotUpdated: 'Plot updated',
    plotUpdateFailed: 'Failed to update plot',
    enterPlotName: 'Please enter a plot name',
    savePlotFirst: 'Please save the plot first, then add crops',
    cropAddFailed: 'Failed to add crop',
    cropRemoveFailed: 'Failed to remove crop',
    cropStatusUpdateFailed: 'Failed to update crop status',
    statusPlanned: 'planned',
    statusPlanted: 'planted',
    statusGrowing: 'growing',
    statusFlowering: 'flowering',
    statusHarvested: 'harvested',
    statusActive: 'active',
  },
  cropPicker: {
    title: 'Select Crop',
    searchPlaceholder: 'Search crops...',
    loadingCrops: 'Loading crops...',
    noCropsFound: 'No crops found',
  },
  livestock: {
    myLivestock: 'My Livestock',
    animal: 'Animal',
    addAnimal: 'Add Animal',
    noLivestock: 'No livestock yet',
    noLivestockHint: 'Add your first animal to track health and events',
    livestockType: 'Livestock Type',
    trackingMode: 'Tracking Mode',
    individual: 'Individual',
    herd: 'Herd',
    herdSize: 'Herd Size',
    herdSizePlaceholder: 'e.g. 12',
    herdNameOptional: 'Herd Name (optional)',
    herdNamePlaceholder: 'e.g. Main Herd',
    nameOptional: 'Name (optional)',
    namePlaceholder: 'e.g. Aster',
    breed: 'Breed',
    selectBreed: 'Select breed...',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    newAnimal: 'New Animal',
    editAnimal: 'Edit Animal',
    addAnimalButton: 'Add Animal',
    saveChanges: 'Save Changes',
    deleteAnimal: 'Delete Animal',
    deleteAnimalConfirm: 'Are you sure you want to delete "{name}"? This will also remove all event history.',
    animalDeleted: 'Animal deleted',
    animalDeleteFailed: 'Failed to delete animal',
    animalAdded: 'Animal added',
    animalAddFailed: 'Failed to add animal',
    animalUpdated: 'Animal updated',
    animalUpdateFailed: 'Failed to update animal',
    animalNotFound: 'Animal not found',
    tagId: 'TAG / EAR TAG ID (optional)',
    tagIdPlaceholder: 'e.g. KE-2024-0042',
    dateOfBirth: 'DATE OF BIRTH (optional)',
    dateOfBirthPlaceholder: 'YYYY-MM-DD',
    lactationStatusLabel: 'LACTATION STATUS (optional)',
    lactation_lactating: 'Lactating',
    lactation_dry: 'Dry',
    lactation_not_applicable: 'N/A',
    invalidDateOfBirth: 'Please enter a valid date (YYYY-MM-DD)',
    selectLivestockType: 'Please select a livestock type',
    loadingLivestockTypes: 'Loading livestock types...',
    type: 'Type',
    breedLabel: 'Breed',
    genderLabel: 'Gender',
    herdSizeLabel: 'Herd Size',
    weight: 'Weight',
    weightValue: '{weight} kg',
    status: 'Status',
    statusActive: 'Active',
    statusSold: 'Sold',
    statusDeceased: 'Deceased',
    statusTransferred: 'Transferred',
    recordEvent: 'Record Event',
    eventHistory: 'Event History',
    noEventsRecorded: 'No events recorded yet',
    sectionMyLivestock: 'MY LIVESTOCK',
    animalsCount: '{count} animal',
    animalsCountPlural: '{count} animals',
    noLivestockYetHint: 'Track your animals for better management',
  },
  livestockEvent: {
    recordEventTitle: 'Record Event',
    eventType: 'Event Type',
    vaccination: 'Vaccination',
    calving: 'Calving',
    healthIssue: 'Health Issue',
    treatment: 'Treatment',
    breeding: 'Breeding',
    weightRecord: 'Weight Record',
    milkRecord: 'Milk Record',
    deworming: 'Deworming',
    sale: 'Sale',
    death: 'Death',
    vaccineName: 'Vaccine Name',
    vaccineNamePlaceholder: 'e.g. FMD, Anthrax',
    weightKg: 'Weight (kg)',
    weightPlaceholder: 'e.g. 350',
    milkLiters: 'Milk (liters)',
    milkPlaceholder: 'e.g. 5.5',
    notesOptional: 'Notes (optional)',
    notesPlaceholder: 'Add any details...',
    recordEventButton: 'Record Event',
    eventRecorded: 'Event recorded',
    eventRecordFailed: 'Failed to record event',
    enterValidWeight: 'Please enter a valid weight',
    enterValidMilk: 'Please enter a valid milk quantity',
  },
  breedPicker: {
    title: 'Select Breed',
    titleWithLivestock: '{livestock} Breeds',
    searchPlaceholder: 'Search breeds...',
    noBreedsAvailable: 'No breeds available',
    noBreedsFound: 'No breeds found',
  },
  extensionWorker: {
    chattingAs: 'Chatting as:',
    sectionExtensionWorker: 'EXTENSION WORKER',
    myFarmers: 'My Farmers',
    myFarmersHint: 'Manage connected farmers',
    pendingRequests: 'Pending Requests',
    pendingRequestsHint: 'Review connection requests',
    connectFarmer: 'Connect Farmer',
    connectFarmerHint: "Enter the farmer's phone number to connect. If they don't have the app yet, a proxy profile will be created that merges when they sign up.",
    phoneNumber: 'PHONE NUMBER',
    phonePlaceholder: '+254 7XX XXX XXX',
    connect: 'Connect',
    verifyAndConnect: 'Verify & Connect',
    connectWithoutVerification: 'Connect without verification',
    connectionRequestSent: 'Connection request sent',
    alreadyConnected: 'Already connected to this farmer',
    connectionFailed: 'Failed to connect',
    connectDescription: "Enter the farmer's phone number to connect. If they don't have the app yet, a proxy profile will be created that merges when they sign up.",
    organization: 'ORGANIZATION',
    connectInfo: 'The farmer will receive a connection request. Once approved, you can chat on their behalf and manage their farm data.',
    noFarmersConnected: 'No farmers connected',
    noFarmersHint: 'Connect with farmers to assist them via the app',
    connectAFarmer: 'Connect a Farmer',
    proxy: 'Proxy',
    noPendingRequests: 'No pending requests',
    noPendingRequestsHint: 'All connection requests have been handled',
    approve: 'Approve',
    reject: 'Reject',
    connectionApproved: 'Connection approved',
    connectionRejected: 'Connection rejected',
    respondFailed: 'Failed to respond',
    awaitingApproval: 'Awaiting farmer approval',
    farmer: 'Farmer',
    extensionWorker: 'Extension Worker',
    unknownFarmer: 'Unknown Farmer',
    unknownEw: 'Unknown EW',
    searchFarmers: 'Search by name or phone',
    loadFarmersFailed: 'Failed to load farmers',
    loadRequestsFailed: 'Failed to load requests',
  },
  a2ui: {
    confirm: 'Confirm',
    enterNumber: 'Enter Value',
    fillForm: 'Fill Details',
    dismissed: 'Dismissed',
    fieldRequired: 'Required',
    fieldMustBePositive: 'Must be a positive number',
    fieldMaxValue: 'Maximum',
    notListed: 'Not listed? Type a name',
    selectDate: 'Select Date',
    date: 'Date',
    selectOptions: 'Select Options',
    selectPlot: 'Select Plot',
    searchPlots: 'Search plots...',
    noPlotsFound: 'No plots found. Add a farm in your profile first.',
    completeProfile: 'Complete Your Profile',
    selectFarmer: 'Select Farmer',
    searchFarmers: 'Search farmers...',
    noFarmersFound: 'No connected farmers found.',
    noChartData: 'No chart data available',
  },
  categories: {
    cereals: 'Cereals',
    legumes: 'Legumes',
    oilseeds: 'Oilseeds',
    vegetables: 'Vegetables',
    fruits: 'Fruits',
    root_crops: 'Root Crops',
    spices: 'Spices',
    cash_crops: 'Cash Crops',
    fibre_crops: 'Fibre Crops',
    fodder: 'Fodder',
    flowers: 'Flowers',
    cattle: 'Cattle',
    poultry: 'Poultry',
    goats: 'Goats',
    sheep: 'Sheep',
    pigs: 'Pigs',
    fish: 'Fish',
    bees: 'Bees',
    other: 'Other',
  },
  otp: {
    title: 'Verify Phone',
    description: 'Enter the 6-digit code sent to {phone}',
    verify: 'Verify',
    verified: 'Phone verified!',
    invalidCode: 'Invalid code. Please check and try again.',
    verifyFailed: 'Verification failed. Please try again.',
    resend: 'Resend Code',
    resendIn: 'Resend in',
    resent: 'New code sent!',
    resendFailed: 'Could not resend code. Please try again.',
    sendFailed: 'Could not send verification code. Please try again.',
  },
  consent: {
    title: 'Connection Consent',
    description: 'By approving, the extension worker will be able to:',
    point1: 'Chat with FarmerChat on your behalf',
    point2: 'View and update your farm profile',
    point3: 'Access your chat history for advisory sessions',
    approve: 'I Approve',
    decline: 'Decline',
    declined: 'Connection declined.',
    privacyNote: 'You can revoke access anytime from Settings.',
  },
  ration: {
    notAvailable: 'Feed recommendations are not available in your region yet.',
    noDevice: 'I need a linked device session to create a diet. Please restart the app and try again.',
    reset: 'Okay, I have reset the feed flow. Tell me when you want to start again.',
    countryFailed: 'I could not determine your country for feed recommendations. Please try again in a moment.',
    countryNotMatched: 'I could not match a feed catalog for your country. Please confirm your location and try again.',
    countryFallbackWarning: 'Using {country} as default location. Update your location in Settings for more accurate results.',
    selectCow: 'I found these cows:',
    selectCowPrompt: 'Reply with a number or type "new" to add another cow.',
    selectBreed: 'Which breed is the cow?',
    selectBreedPrompt: 'Reply with the number, name, or type your own breed.',
    selectBreedNameOnly: 'Please type the breed name.',
    breedsFailed: 'I could not load breeds right now. Please try again.',
    invalidCow: 'Please reply with a valid cow number or type "new" to add another cow.',
    batchNotSupported: 'I can generate a feed plan for one cow at a time. Please select a cow by number, and we can do the next one after.',
    enterName: "What is the cow's name?",
    enterWeight: 'What is her approximate body weight in kg?',
    invalidWeight: 'Please provide the weight in kg (for example, 350). Must be between {min} and {max} kg.',
    enterMilk: 'How many liters of milk does she produce per day? (use 0 if dry)',
    invalidMilk: 'Please provide the daily milk quantity in liters (for example, 12). Use 0 if dry.',
    isPregnant: 'Is she currently pregnant? (yes/no)',
    enterPregnancyDays: 'How many days pregnant is she?',
    invalidPregnancyDays: 'Please provide the pregnancy days as a number between {min} and {max} (for example, 120).',
    cowCreateFailed: 'I could not save the cow profile right now. Please try again.',
    cowIdMissing: 'I could not identify the cow profile. Please try again.',
    dietFailed: 'I could not generate the diet right now. Please try again later.',
    dietReady: 'Would you like to follow this diet? (yes/no)',
    confirmFollow: 'Please reply yes or no. Do you want to follow this diet?',
    dietReadyNoFollow: 'I have your diet ready. Ask me for the schedule anytime.',
    followStarted: 'You are now following this diet.',
    followFailed: 'I could not start the follow-up reminders right now.',
    followDeclined: 'Okay, I will not start reminders. Ask me anytime for the schedule.',
    schedule: 'Here is your feeding schedule:',
    scheduleFailed: 'I could not load the schedule right now.',
    history: 'Here is your diet history:',
    historyFailed: 'I could not load diet history right now.',
    unfollowed: 'Diet follow-up stopped.',
    unfollowFailed: 'I could not stop the diet right now.',
    doneHelp: 'You can ask me to show the diet schedule, diet history, or start a new feed plan.',
    continueSetup: 'Please continue with the feed setup so I can complete the diet.',
    feedPlan: 'Feed Plan',
    cached: 'Cached',
    kgPerDay: 'kg/day',
    kg: 'kg',
    dailyCost: 'Daily cost',
    day: 'day',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    scheduleFor: 'Feeding schedule for {cowName}',
    nextCheckIn: 'Next check-in: {date}',
    statusActive: 'Active',
    statusFollowing: 'Following',
    statusCreated: 'Created',
    statusArchived: 'Archived',
  },
};

export type StringsType = typeof en;
