export const LANGUAGES = {
  hi: { name: 'Hindi', nativeName: 'हिन्दी', script: 'Devanagari script' },
  te: { name: 'Telugu', nativeName: 'తెలుగు', script: 'Telugu script' },
  kn: { name: 'Kannada', nativeName: 'ಕನ್ನಡ', script: 'Kannada script' },
  mr: { name: 'Marathi', nativeName: 'मराठी', script: 'Devanagari script' },
  gu: { name: 'Gujarati', nativeName: 'ગુજરાતી', script: 'Gujarati script' },
  ta: { name: 'Tamil', nativeName: 'தமிழ்', script: 'Tamil script' },
  bn: { name: 'Bengali', nativeName: 'বাংলা', script: 'Bengali script' },
  ml: { name: 'Malayalam', nativeName: 'മലയാളം', script: 'Malayalam script' },
  pa: { name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', script: 'Gurmukhi script' },
  or: { name: 'Odia', nativeName: 'ଓଡ଼ିଆ', script: 'Odia script' },
  as: { name: 'Assamese', nativeName: 'অসমীয়া', script: 'Assamese script' },
  ne: { name: 'Nepali', nativeName: 'नेपाली', script: 'Devanagari script' },
  sw: { name: 'Swahili', nativeName: 'Kiswahili', script: 'Latin script' },
  am: { name: 'Amharic', nativeName: 'አማርኛ', script: 'Ethiopic script' },
  aa: { name: 'Afar', nativeName: 'Qafar', script: 'Latin script' },
  om: { name: 'Oromo', nativeName: 'Afaan Oromoo', script: 'Latin script' },
  ti: { name: 'Tigrinya', nativeName: 'ትግርኛ', script: 'Ethiopic script' },
  ha: { name: 'Hausa', nativeName: 'Hausa', script: 'Latin script' },
  yo: { name: 'Yoruba', nativeName: 'Yorùbá', script: 'Latin script' },
  zu: { name: 'Zulu', nativeName: 'isiZulu', script: 'Latin script' },
  ig: { name: 'Igbo', nativeName: 'Igbo', script: 'Latin script' },
  rw: { name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', script: 'Latin script' },
  so: { name: 'Somali', nativeName: 'Soomaali', script: 'Latin script' },
  vi: { name: 'Vietnamese', nativeName: 'Tiếng Việt', script: 'Latin with diacritics' },
  th: { name: 'Thai', nativeName: 'ไทย', script: 'Thai script' },
  id: { name: 'Indonesian', nativeName: 'Bahasa Indonesia', script: 'Latin script' },
  fil: { name: 'Filipino', nativeName: 'Filipino', script: 'Latin script' },
  ms: { name: 'Malay', nativeName: 'Bahasa Melayu', script: 'Latin script' },
  my: { name: 'Burmese', nativeName: 'မြန်မာ', script: 'Myanmar script' },
  km: { name: 'Khmer', nativeName: 'ខ្មែរ', script: 'Khmer script' },
  lo: { name: 'Lao', nativeName: 'ລາວ', script: 'Lao script' },
  es: { name: 'Spanish', nativeName: 'Español', script: 'Latin script' },
  fr: { name: 'French', nativeName: 'Français', script: 'Latin script' },
  de: { name: 'German', nativeName: 'Deutsch', script: 'Latin script' },
  pt: { name: 'Portuguese', nativeName: 'Português', script: 'Latin script' },
  it: { name: 'Italian', nativeName: 'Italiano', script: 'Latin script' },
  nl: { name: 'Dutch', nativeName: 'Nederlands', script: 'Latin script' },
  pl: { name: 'Polish', nativeName: 'Polski', script: 'Latin script' },
  uk: { name: 'Ukrainian', nativeName: 'Українська', script: 'Cyrillic script' },
  ru: { name: 'Russian', nativeName: 'Русский', script: 'Cyrillic script' },
  ro: { name: 'Romanian', nativeName: 'Română', script: 'Latin script' },
  el: { name: 'Greek', nativeName: 'Ελληνικά', script: 'Greek script' },
  cs: { name: 'Czech', nativeName: 'Čeština', script: 'Latin script' },
  sv: { name: 'Swedish', nativeName: 'Svenska', script: 'Latin script' },
  ar: { name: 'Arabic', nativeName: 'العربية', script: 'Arabic script (RTL)' },
  fa: { name: 'Persian', nativeName: 'فارسی', script: 'Perso-Arabic script (RTL)' },
  tr: { name: 'Turkish', nativeName: 'Türkçe', script: 'Latin script' },
  he: { name: 'Hebrew', nativeName: 'עברית', script: 'Hebrew script (RTL)' },
  ur: { name: 'Urdu', nativeName: 'اردو', script: 'Nastaliq script (RTL)' },
  'zh-CN': { name: 'Chinese (Simplified)', nativeName: '简体中文', script: 'Simplified Chinese' },
  'zh-TW': { name: 'Chinese (Traditional)', nativeName: '繁體中文', script: 'Traditional Chinese' },
  ja: { name: 'Japanese', nativeName: '日本語', script: 'Japanese script' },
  ko: { name: 'Korean', nativeName: '한국어', script: 'Hangul script' },
};
